version: '3'
services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    volumes:
      - ./data/mosquitto:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
  nodered:
    container_name: nodered
    image: nodered/node-red
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./data/nodered:/data
    ports:
      - "1880:1880"
    links:
      - redis
      - mqtt
    restart: always
  redis:
    container_name: redis
    image: redis
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./data/redis:/data
    ports:
      - "127.0.0.1:6379:6379"
    restart: always
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXD_HTTP_BIND_ADDRESS=0.0.0.0:8086
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
      - INFLUXD_ENGINE_PATH=/data/engine
      - INFLUXD_BOLT_PATH=/data/influxd.bolt
    volumes:
      # Data persistency
      - ./data/influxdb/data:/data
    restart: always
  io7api:
    container_name: io7api
    image: mynode
    environment:
      #- ADMIN_ID=admin
      #- ADMIN_PASSWORD=password
      #- DYNSEC_FILE=mqtt/dynamic-security.json
      - MQTT_CONN=mqtt://mqtt
    volumes:
      - ./data/io7-api-server:/home/node/app
      - ./data/mosquitto/config:/home/node/app/mqtt
    ports:
      - "2009:2009"
    links:
      - redis
      - mqtt
    restart: always
  io7mgmt:
    container_name: io7mgmt
    image: mynode
    volumes:
      - ./data/io7-management-web:/home/node/app
    ports:
      - "3000:3000"
    restart: always
  io7gwd:
    container_name: io7gwd
    image: mynode
    environment:
      - API_SERVER=http://io7api:2009
      - MQTT_CONN=mqtt://mqtt
    volumes:
      - ./data/gateway-server:/home/node/app
    links:
      - io7api
      - mqtt
    restart: always
